zuul:
  prefix: /RetailsApiGatway
  routes:
    resource:
    PRODUCT-SERVICE:
      path: /mukesh/**
      service-id: PRODUCT-SERVICE
    SHOPPING-SERVICE: 
      path: /shoppingcart/**
      service-id: SHOPPING-SERVICE
      
    employeeUI:
      serviceId: EmployeeDashBoard
  host:
    socket-timeout-millis: 30000
      
server:
  port: 2509
  
eureka:
  client:
    registerwitheureka: true
    fetchregistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      preferIpAddress: true
  
spring:
  application:
    name: zuul-apigatway

endpoints:
  routes:
    enabled-by-default: true
  
  restart:
    enabled-by-default: true
   
  shutdown: 
     enabled-by-default: true
     
#management:
#  security:
#    enabled: false 
#    basic: 
#      enable: false   


   
    
   